[window]
startup_mode = "Maximized"
decorations = "Buttonless"
opacity = 0.75
blur = true


[font]
size = 14
normal = { family = "Liga SFMono Nerd Font", style = "Regular" }
bold = { family = "Liga SFMono Nerd Font", style = "Bold" }
italic = { family = "Liga SFMono Nerd Font", style = "Italic" }
bold_italic = { family = "Liga SFMono Nerd Font", style = "Bold Italic" }


[colors.primary]
background = "#000000"
foreground = "#cdd6f4"

[mouse]
hide_when_typing = true
bindings = [
    { mouse = "Right", action = "Copy" },
]

[terminal]
shell = { program = "/bin/zsh", args = ["-l"] }
