Completion:
  AllScopes: Yes
  ArgumentLists: FullPlaceholders
  HeaderInsertion: IWYU
InlayHints:
  Enabled: Yes
  ParameterNames: Yes
  DeducedTypes: Yes
  Designators: Yes
  BlockEnd: No
  DefaultArguments: No
Hover:
  ShowAKA: Yes
Diagnostics:
  UnusedIncludes: Strict
  MissingIncludes: Strict
  ClangTidy:
    Add:
      - bugprone-*
      - performance-*
    Remove:
      - bugprone-easily-swappable-parameters
    FastCheckFilter: Loose
---
If:
  PathMatch: [.*\.c$, .*\.h$]
CompileFlags:
  Add: [-std=c11]
---
If:
  PathMatch: [.*\.(cpp|cc|cxx|hpp|hxx)$]
CompileFlags:
  Add: [-std=c++20]
